env:
  es6: true
  node: true
  jest/globals: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  extends: standard
plugins:
  - "jest"
rules: {}
